spring:
  application:
    name: powertracker
  profiles:
    active: @activatedProperties@

logging:
  level:
    root: INFO
    com.flabbyninja.powertracker: DEBUG

credentials:
  clear: PropertyInClear
  enc: ENC(015xsE4ll/TLAVQclEWKKw==)