spring:
  application:
    name: powertracker
  profiles:
    active: @activatedProperties@
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

logging:
  level:
    root: INFO
    com.flabbyninja.powertracker: DEBUG

credentials:
  clear: PropertyInClear
  enc: ENC(015xsE4ll/TLAVQclEWKKw==)
