spring:
  application:
    name: powertracker
  profiles:
    active: @activatedProperties@

logging:
  level:
    root: INFO

jasypt:
  encryptor:
    bean: encryptorBean

server:
  servlet:
    context-path: /api